final String sales_order_cart_promotions_tabelname='sales_order_cart_promotions';
final String sales_order_cart_promotions_id='id';

final String sales_order_cart_promotions_sales_order_cart_id='sales_order_cart_id';
final String sales_order_cart_promotions_discount_type='discount_type';
final String sales_order_cart_promotions_discount_percentage='discount_percentage';
final String sales_order_cart_promotions_discount_amount='discount_amount';
final String sales_order_cart_promotions_promotion_id='promotion_id';
final String sales_order_cart_promotions_promotion_type='promotion_type';
final String sales_order_cart_promotions_promotion_bonus_item_id='promotion_bonus_item_id';
final String sales_order_cart_promotions_promotion_bonus_quantity='promotion_bonus_quantity';
final String sales_order_cart_promotions_created_at='created_at';
final String sales_order_cart_promotions_updated_at='updated_at';
